#!/bin/sh

XDG_DOWNLOAD_DIR=$HOME/Downloads

echo "
XDG_DOWNLOAD_DIR=\"$XDG_DOWNLOAD_DIR\"
XDG_DESKTOP_DIR=\"$XDG_DOWNLOAD_DIR\"
XDG_PICTURES_DIR=\"$XDG_DOWNLOAD_DIR/Pictures\"
XDG_MUSIC_DIR=\"$XDG_DOWNLOAD_DIR/Music\"
XDG_VIDEOS_DIR=\"$XDG_DOWNLOAD_DIR/Videos\"
XDG_DOCUMENTS_DIR=\"$XDG_DOWNLOAD_DIR/Documents\"
XDG_PUBLICSHARE_DIR=\"$XDG_DOWNLOAD_DIR/Public\"
XDG_TEMPLATES_DIR=\"$XDG_DOWNLOAD_DIR/Templates\"
" > $XDG_CONFIG_HOME/user-dirs.dirs

