#! /bin/sh

#
# Bspwm configuration
#

desktops.sh 2

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio        0.5
bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config single_monocle     true

#
# Window rules
#

SCREEN_DIMENSIONS=$(xdpyinfo | grep dimensions | awk '{print $2}')
SCREEN_WIDTH=$(echo "$SCREEN_DIMENSIONS" | cut -d'x' -f1)
SCREEN_HEIGHT=$(echo "$SCREEN_DIMENSIONS" | cut -d'x' -f2)

FLOATING_WIDTH=$(($SCREEN_WIDTH * 7 / 8))
FLOATING_HEIGHT=$(($SCREEN_HEIGHT * 7 / 8))
FLOATING_X=$(( ($SCREEN_WIDTH - $FLOATING_WIDTH) / 2 ))
FLOATING_Y=$(( ($SCREEN_HEIGHT - $FLOATING_HEIGHT) / 2 ))
FLOATING_RECTANGLE="$FLOATING_WIDTH"x"$FLOATING_HEIGHT"+"$FLOATING_X"+"$FLOATING_Y"

bspc rule -a dropdown_terminal sticky=on state=floating hidden=on \
    rectangle=$FLOATING_RECTANGLE
bspc rule -a dropdown_browser sticky=on state=floating hidden=on \
    rectangle=$FLOATING_RECTANGLE

bspc rule -a Sxiv state=fullscreen
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=fullscreen

#
# Starting applications
#

picom --config $HOME/.picom.conf &

$HOME/.scripts/xdf/dropdown-terminal.sh &
$HOME/.scripts/xdf/dropdown-browser.sh &

sxhkd &

unclutter &
$HOME/.scripts/xdf/keyboard-layout-notifications.sh &
$HOME/.scripts/xdf/polybar.sh top &
$HOME/.scripts/xdf/polybar.sh bottom &
classic-wallpaper.sh

dex -a

