#! /bin/sh

SCRIPTS_DIR="$HOME/.scripts/xdf"

#
# Bspwm configuration
#

for m in $(bspc query -M)
do
    desktops.sh 3 $m
done

bspc config border_width        2
bspc config window_gap          10

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true

bspc config focus_follows_pointer true

bspc config pointer_modifier    mod4
bspc config pointer_action1     move
bspc config pointer_action2     resize_side
bspc config pointer_action3     resize_corner

bspc config external_rules_command "$SCRIPTS_DIR/bspwm_rules.sh"

#
# Starting applications
#

AUTOSTART="$SCRIPTS_DIR/autostart"

# asynchronous
find "$AUTOSTART/async" -type f -name "*.sh" | 
    while read script
    do sh "$script" &
    done

# synchronous
find "$AUTOSTART/sync"  -type f -name "*.sh" | xargs -r sh

