#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.62
bspc config borderless_monocle   true
bspc config gapless_monocle      true

