#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a scratchpad sticky=on state=floating hidden=on

dex -a

picom --config $HOME/.picom.conf &

unclutter &
sxhkd &

$HOME/bin/xdf/enable-scratchpad.sh
polybar top & polybar bottom &

$HOME/bin/xdf/classic-wallpaper.sh

